### ISSUE TITLE
Battery cameras connected to NVR keep waking up

### ISSUE THREAD

**Issue by sjonez** [starkillerOG/reolink_aio#83] opened 2024-10-23 16:17 UTC
Since NVR firmware 3.5 you can now add battery cameras to some reolink NVRs (https://support.reolink.com/hc/en-us/articles/900000602543-Introduction-to-Hardware-Versions-of-Reolink-NVRs/)

I have an RLN8-410 NVR and an Argus PT battery camera connected to the NVR, which can be detected and configured via the NVR just like any other PoE camera, however it doesn't look like it gets exposed as a battery camera in the same way, which means Home Assistant is keeping the camera from going into standby (I assume there are a list of APIs that will wake battery cameras up)

The first night after adding the camera into HA, the 100% battery drained overnight 😢 

I'm hoping you can add the ability to detect and treat these cameras as battery cameras (and maybe even retrieve the battery %, which you can see on the NVR) to prevent waking them up so frequently.

**Comment by starkillerOG** [comment] 2024-10-23 18:14
This is a know issue and also the reason I did not list the NVRs under the battery compatibility section of the docs.

With the Reolink Home Hub it will work as expected, conserving the battery live and giving you battery info.

Reolink firmware engineers are busy improving the NVR firmware to make it function properly with Battery Camera's. At the moment HomeAssistant will not recognize battery cams as beeing battery cams but just as regular cams when connected to a NVR instead of a Home Hub. Unfortunately I can not provide a ETA for new firmware, but it is coming.

In the meantime I would advise disabling all entities of the Reolink Battery Camera in HomeAssistant, that will stop the requests to the battery camera and will conserve the battery while still being able to use the other connected cams inside HomeAssistant.

**Comment by starkillerOG** [comment] 2024-10-23 18:19
On the Reolink Facebook group, Reolink is running a beta trial for their RLN8-410 firmware. (I saw it beeing anounched a few days ago).
Have not tried the new beta firmware yet, but you could try and see if that already includes the fixes I have requested.

**Comment by starkillerOG** [comment] 2024-11-23 11:06
I looked into this, but also non-battery cameras respond on the BatteryInfo command with values which I cannot distinguish from a true battery camera.
So the problem is knowing if a camera has a battery yes or no.

**Comment by starkillerOG** [comment] 2024-11-23 11:33
Nice, in that case I will close this issue.

**Closed by starkillerOG** 2024-11-23 11:33 UTC
