### ISSUE TITLE
Camera events not transmitted to HA

### ISSUE THREAD

**Issue by cdl86** [starkillerOG/reolink_aio#92] opened 2024-12-04 23:17 UTC
**Describe the bug**
Camera events such as Person and Vehicle are sometimes not transmitted into the Reolink integration for my Duo 2 POE camera.  For example, I will get a notification of a person from the Reolink app, but no action from my HA automation which should send me a snapshot picture.

When I check the Person Motion entity of that camera in HA, the motion event is completely missing.  When this missed event happens, I downloaded the diagnostic log of the device.  I see that it switched to "event connection": "ONVIF push" rather than "event connection": "TCP push".  If I disable and then re-enable the device, and a new event happens, it goes back to TCP push and transmits the event successfully.

@starkillerOG , in core issue #124208 i saw that you made an update to the core relating to TCP push.  Originally I was having the same issue with a different device (Doorbell Wifi), and searching forums led me to see that update, which seemed to fix the problem for the doorbell after I upgraded HA to 11.3.  But now, it's also happening to my Duo 2 POE device.

**To Reproduce**
Steps to reproduce the behavior. Pleaee provide the error from the log if possible.

**Expected behavior**

**Screenshots**

**Environment:**
        "model": "Reolink Duo 2 PoE",
        "hardware version": "IPC_529B17B8MP",
        "firmware version": "v3.0.0.3471_2406115691",
 
    "installation_type": "Home Assistant OS",
    "version": "2024.11.3",
    "dev": false,
    "hassio": true,
    "virtualenv": false,
    "python_version": "3.12.4",
    "docker": true,
    "arch": "aarch64",
    "timezone": "America/Los_Angeles",
    "os_name": "Linux",
    "os_version": "6.6.31-haos-raspi",
    "supervisor": "2024.11.4",
    "host_os": "Home Assistant OS 13.2",
    "docker_version": "27.2.0",
    "chassis": "embedded",
    "run_as_root": true

**Additional context**

**Comment by starkillerOG** [comment] 2024-12-05 07:47
@cdl86 thank you for reporting the bug.
This is indeed a bug in HomeAssistant 2024.11.3, but it is already fixed in HA 2024.12.0.
Please update and see if the issue is properly fixed for you.
If not please let me know.

If you appreciate the reolink integration and want to support its development, please consider [sponsering](https://github.com/sponsors/starkillerOG) the upstream library or purchase Reolink products through [this affiliate link](https://reolink.pxf.io/q44QWq).

**Closed by starkillerOG** 2024-12-05 07:47 UTC
